### ISSUE TITLE
Format of input data

### ISSUE THREAD

**Issue by ValentinaPy** [rknaebel/discopy#13]
Hi!

I would like to run your parser, but from the instructions it is not really clear what the input format is supposed to be (besides the fact that it should be json). How should I transform the PDTB data to make it work with your parser?

Thank you!

**Comment by rknaebel** [comment]
I know it's late, but finally, I have got an improved version. 
In addition to #17 (basic processing), one can load the PDTB (CoNLL 2016 shared task JSON format) directly for training and prediction. Depending on your use case, you could also convert the full PDTB to this JSON format, but I am still working on it (experimental).
