### ISSUE TITLE
Error running

### ISSUE THREAD

**Issue by anamm1025** [rknaebel/discopy#17]
Hi,
I want to run this parser for only connective extraction, I do not want to train the model.
The following is the error I'm getting. Am I doing something wrong? Any help will be appreciated.
![image](https://user-images.githubusercontent.com/14789953/126491714-52658c53-56e0-47a2-8182-ace51f99f68a.png)

**Comment by rknaebel** [comment]
You cannot, unfortunately, select individual components of a stored pipeline easily. However, you could adjust the config.json file of the corresponding model to include only the connective component (just remove the other entries that follow).

For data preparation, I recommend using discopy-data in combination with the parser as follows (I guess the interface changed over the last days):
1. traditional feature-based parser: `discopy-tokenize -i examples/wsj_0336 | discopy-add-parses -c | discopy-parse lin models/lin`
2. neural parser: `discopy-tokenize --tokenize-only -i examples/wsj_0336 | discopy-nn-parse bert-base-cased models/pipeline-bert-2`

You could also first process your documents,  store them in a single file and then parse this file by either parser pipeline:
1. `discopy-tokenize -i examples/wsj_0336 | discopy-add-parses -c > dataset.json`
2. `discopy-tokenize -i examples/wsj_034X | discopy-add-parses -c >> dataset.json`
3. `discopy-nn-parse bert-base-cased models/pipeline-bert-2 -i dataset.json`

_Note: `discopy-tokenize` splits text files into multiple documents by three or more consecutive newlines (r'\n\n\n+')_

**Comment by anamm1025** [comment]
> You cannot, unfortunately, select individual components of a stored pipeline easily. However, you could adjust the config.json file of the corresponding model to include only the connective component (just remove the other entries that follow).
> 
> For data preparation, I recommend using discopy-data in combination with the parser as follows (I guess the interface changed over the last days):
> 
> 1. traditional feature-based parser: `discopy-tokenize -i examples/wsj_0336 | discopy-add-parses -c | discopy-parse lin models/lin`
> 2. neural parser: `discopy-tokenize --tokenize-only -i examples/wsj_0336 | discopy-nn-parse bert-base-cased models/pipeline-bert-2`
> 
> You could also first process your documents, store them in a single file and then parse this file by either parser pipeline:
> 
> 1. `discopy-tokenize -i examples/wsj_0336 | discopy-add-parses -c > dataset.json`
> 2. `discopy-tokenize -i examples/wsj_034X | discopy-add-parses -c >> dataset.json`
> 3. `discopy-nn-parse bert-base-cased models/pipeline-bert-2 -i dataset.json`
> 
> _Note: `discopy-tokenize` splits text files into multiple documents by three or more consecutive newlines (r'\n\n\n+')_

Thanks for your response. I have been able to run first two steps successfully. However, this repository doesn't contain 'models' folder, as well as config files. Can you please upload those too?

**Comment by rknaebel** [comment]
To not blow up the repository with models' histories, I put them under releases:
https://github.com/rknaebel/discopy/releases
