### ISSUE TITLE
prediction doesn't work

### ISSUE THREAD

**Issue by MariRazno** [rknaebel/discopy#19]
There is an error
 /bin/bash: discopy-predict: command not found
 
 Output of the command 
 !compgen -ac | grep discopy
 is:
discopy-nn-predict
discopy-add-parses
discopy-eval
discopy-parse
discopy-train
discopy-extract
discopy-nn-parse
discopy-add-annotations
discopy-tokenize
discopy-nn-train

There is no discopy-predict

**Comment by rknaebel** [comment]
Sorry, I missed the entry in the setup file. Should be added now.
