### ISSUE TITLE
Extend implicit relation classification

### ISSUE THREAD

**Issue by rknaebel** [rknaebel/discopy#3]
Based on the provided implicit sense classifier, add more features such as dependency rules and word pairs for better results.
Also, it might be useful to select informative features from all extracted features (as shown in Lin et al.)

**Comment by Himbiss** [comment]
Hey, I would like to work on this issue but I cannot assign it to myself by dragging it in the project board. I guess that's because I am not yet a collaborator. Could you assign me?
